import React, { useMemo, useState } from 'react';
import { AlertTriangle, Bug, CheckCircle2, FileWarning, KeyRound, LockKeyhole, RefreshCw, ShieldAlert, ShieldCheck } from 'lucide-react';
import type { SaqlainFinding, SaqlainSecuritySummary } from '../types/saqlain';

interface Props { activeProjectName?: string }
const seed: SaqlainFinding[] = [
  { id:'saq-state', title:'Authoritative project state is browser-persisted', description:'localStorage should not be treated as a protected system of record for project or BOQ data.', category:'privacy', severity:'medium', status:'open', recommendation:'Move authoritative records to authenticated server-side storage with project-level authorization and audit logging.', evidence:'gouse_ai_projects / gouse_ai_boq_items', createdAt:new Date().toISOString(), updatedAt:new Date().toISOString() },
  { id:'saq-ai', title:'AI-driven mutations need an authorization gateway', description:'AI-generated actions that change project or BOQ data should be validated and authorized before execution.', category:'ai-actions', severity:'high', status:'open', recommendation:'Validate action schema, actor permissions, project membership and approval requirements before mutation.', createdAt:new Date().toISOString(), updatedAt:new Date().toISOString() },
];
const rank: Record<SaqlainFinding['severity'],number> = { critical:5, high:4, medium:3, low:2, info:1 };

export const SaqlainSecurityView: React.FC<Props> = ({ activeProjectName }) => {
  const [findings,setFindings] = useState(seed); const [scanning,setScanning] = useState(false); const [summary,setSummary] = useState<SaqlainSecuritySummary|null>(null);
  const ordered = useMemo(()=>[...findings].sort((a,b)=>rank[b.severity]-rank[a.severity]),[findings]);
  const risk = Math.min(100, findings.filter(f=>f.status!=='resolved').reduce((s,f)=>s+rank[f.severity]*8,0));
  async function scan(){ setScanning(true); try { const r=await fetch('/api/security/saqlain/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:activeProjectName||'Gouse AI workspace'})}); if(!r.ok) throw new Error('scan failed'); const data=await r.json(); setFindings(data.findings||[]); setSummary(data); } catch { setSummary({agent:'Saqlain AI Agent',target:activeProjectName||'Gouse AI workspace',scannedAt:new Date().toISOString(),riskScore:risk,findings,checks:[{name:'Scanner API',status:'warn',detail:'Server scanner unavailable; local findings retained.'}]}); } finally { setScanning(false); } }
  return <section className="max-w-7xl mx-auto px-4 lg:px-8 py-6 space-y-5">
    <div className="rounded-2xl border border-cyan-500/20 bg-slate-900/90 p-5"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-cyan-500/10 border border-cyan-400/20 flex items-center justify-center"><ShieldCheck className="w-6 h-6 text-cyan-300"/></div><div><div className="text-[11px] uppercase tracking-[0.18em] text-cyan-300 font-mono">Cybersecurity & Security Operations</div><h2 className="text-2xl font-semibold text-white">Saqlain AI Agent</h2></div></div><p className="mt-3 text-sm text-slate-400">Security controls for identity, secrets, APIs, files, dependencies, AI actions and project access. Scope: <span className="text-slate-200">{activeProjectName||'Gouse AI workspace'}</span>.</p></div><button onClick={scan} disabled={scanning} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50"><RefreshCw className={\`w-4 h-4 ${scanning?'animate-spin':''}\`}/>{scanning?'Scanning…':'Run Security Scan'}</button></div></div>
    <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4"><Metric label="Risk Score" value={\`${risk}/100\`} icon={ShieldAlert}/><Metric label="Critical" value={String(findings.filter(f=>f.severity==='critical'&&f.status!=='resolved').length)} icon={AlertTriangle}/><Metric label="High" value={String(findings.filter(f=>f.severity==='high'&&f.status!=='resolved').length)} icon={Bug}/><Metric label="Open Findings" value={String(findings.filter(f=>f.status!=='resolved').length)} icon={FileWarning}/></div>
    <div className="grid lg:grid-cols-[1fr_320px] gap-5"><div className="rounded-2xl border border-slate-800 bg-slate-900/80 overflow-hidden"><div className="px-5 py-4 border-b border-slate-800"><h3 className="font-semibold text-white">Security Findings</h3><p className="text-xs text-slate-500 mt-1">Prioritized by severity and status.</p></div><div className="divide-y divide-slate-800">{ordered.map(f=><article key={f.id} className="p-5"><div className="flex flex-col lg:flex-row lg:justify-between gap-3"><div><div className="flex items-center gap-2"><Badge severity={f.severity}/><span className="text-[10px] uppercase text-slate-500 font-mono">{f.category}</span></div><h4 className="mt-2 text-sm font-semibold text-white">{f.title}</h4><p className="mt-1.5 text-xs leading-5 text-slate-400">{f.description}</p><div className="mt-3 rounded-lg bg-slate-950/70 border border-slate-800 p-3 text-xs"><div className="text-cyan-300 font-medium">Recommendation</div><div className="text-slate-400 mt-1">{f.recommendation}</div></div>{f.evidence&&<div className="mt-2 text-[11px] text-slate-600 font-mono">Evidence: {f.evidence}</div>}</div><button disabled={f.status==='resolved'} onClick={()=>setFindings(x=>x.map(v=>v.id===f.id?{...v,status:'resolved',updatedAt:new Date().toISOString()}:v))} className="h-fit inline-flex items-center gap-1.5 rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-300 disabled:opacity-40">{f.status==='resolved'?<><CheckCircle2 className="w-3.5 h-3.5"/>Resolved</>:'Resolve'}</button></div></article>)}</div></div><aside className="space-y-4"><div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><h3 className="font-semibold text-white flex items-center gap-2"><LockKeyhole className="w-4 h-4 text-cyan-300"/>Security Domains</h3><div className="mt-4 space-y-3">{[['Identity & Access','Authentication and project membership'],['Secrets','API keys and environment configuration'],['AI Actions','Authorization before AI-driven mutations'],['Files','Uploads, parsing and content handling'],['APIs','Rate limits and validation'],['Dependencies','Package vulnerability hygiene']].map(([a,b])=><div key={a} className="flex items-start gap-2.5"><KeyRound className="w-4 h-4 text-slate-500"/><div><div className="text-xs text-slate-200">{a}</div><div className="text-[11px] text-slate-500">{b}</div></div></div>)}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><h3 className="font-semibold text-white">Latest Scan</h3><div className="mt-3 text-xs text-slate-400">{summary?.scannedAt?new Date(summary.scannedAt).toLocaleString():'No server scan recorded yet.'}</div></div></aside></div>
  </section>;
};
const Metric=({label,value,icon:Icon}:{label:string;value:string;icon:React.ComponentType<{className?:string}>})=><div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4"><div className="flex items-center justify-between"><div className="text-[11px] uppercase tracking-wider text-slate-500 font-mono">{label}</div><Icon className="w-4 h-4 text-cyan-300"/></div><div className="mt-2 text-2xl font-semibold text-white">{value}</div></div>;
const Badge=({severity}:{severity:SaqlainFinding['severity']})=><span className="text-[10px] uppercase tracking-wider font-mono px-2 py-1 rounded border text-cyan-300 border-cyan-400/20 bg-cyan-500/10">{severity}</span>;
